# $DOCKER_USER and $DOCKER_PASS in Settings > Environment Variables

language: bash

sudo: false

env:
  - DOCKERFILE=Dockerfile.ubuntu DOCKERTAG=ubuntu-14.04
  #- DOCKERFILE=Dockerfile.ubuntu-16.04 DOCKERTAG=ubuntu-16.04
  #- DOCKERFILE=Dockerfile.centos DOCKERTAG=centos-7
  #- DOCKERFILE=Dockerfile.debian DOCKERTAG=debian-jessie
  #- DOCKERFILE=Dockerfile.debian-jessie-toollabs DOCKERTAG=debian-jessie-toollabs

services:
  - docker

install:
  - COMMIT=${TRAVIS_COMMIT::8} ;
  - REPO=drtrigon/docker-arduino ;
  - LATEST=ubuntu-14.04 ;
  - docker login -u $DOCKER_USER -p $DOCKER_PASS ;
  - docker build -f $DOCKERFILE -t $REPO:$COMMIT . ;
  - docker tag $REPO:$COMMIT $REPO:$DOCKERTAG ;
  # - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ;
  - if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
      docker tag $REPO:$COMMIT $REPO:latest ;
    fi

script:
  - docker images ;
#  - docker run -t -d --name testing $REPO:$COMMIT bin/bash ;
#  - docker ps -l ;
#  - docker exec -t testing apt-get install -y git ;
#  - docker exec -t testing git clone https://github.com/drtrigon/sketchbook.git ;
#  - docker exec -t testing arduino --verify --board "arduino:avr:nano:cpu=atmega328" --verbose --preserve-temp-files sketchbook/MultiWii_2_4/MultiWii/MultiWii.ino ;
#  - docker stop testing ;
#  - docker rm testing ;

  - sudo apt-get install git ;
  - git clone https://github.com/drtrigon/sketchbook.git ;
  - docker run -t --rm -v $PWD/sketchbook:. $REPO:$COMMIT ls -la ;
  - docker run -t --rm -v $PWD/sketchbook:. $REPO:$COMMIT eval echo ~$USER ;
  - docker run -t --rm -v $PWD/sketchbook:. $REPO:$COMMIT arduino --verify --board "arduino:avr:nano:cpu=atmega328" --verbose --preserve-temp-files sketchbook/MultiWii_2_4/MultiWii/MultiWii.ino ;

  - docker rmi $REPO:$COMMIT
  - docker images ;
  - docker container ls ;
  - docker ps -l ;
  # Upload to docker if it's on the master branch
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
      docker push $REPO ;
    fi

#after_success:
#  - |-
#    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
#      if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
#        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/drtrigon%2Fdocker-file-metadata-wikibot/requests ;
#        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/drtrigon%2Finstall-file-metadata-wikibot/requests ;
#      fi ;
#    fi

# re-trigger docker-sketchbook ...?

# use this manual run method also for docker-sketchbook instead of Dockerfile

notifications:
  email: false
