# $DOCKER_USER, $DOCKER_PASS (hide) and $TRAVIS_TOKEN (hide) in Settings > Environment Variables
# Triggering builds (get TOKEN): https://docs.travis-ci.com/user/triggering-builds/

language: bash

sudo: false

env:
  matrix:
    - DOCKERFILE=Dockerfile DOCKERTAG=ubuntu-16.04

services:
  - docker

install:
  - COMMIT=${TRAVIS_COMMIT::8} ;
  - REPO=drtrigon/docker-arduino ;
  - LATEST=ubuntu-16.04 ;
  - docker login -u $DOCKER_USER -p $DOCKER_PASS ;
  - docker build -f $DOCKERFILE -t $REPO:$COMMIT . ;
  - docker tag $REPO:$COMMIT $REPO:$DOCKERTAG ;
  # - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ;
  - if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
      docker tag $REPO:$COMMIT $REPO:latest ;
    fi

script:
#  - docker images ;
#  - git clone https://github.com/drtrigon/sketchbook.git ;
#  - docker run -t --rm -v $PWD/sketchbook:/sketchbook $REPO:$COMMIT arduino --verify --board "arduino:avr:nano:cpu=atmega328" --verbose --preserve-temp-files sketchbook/MultiWii_2_4/MultiWii/MultiWii.ino ;
#  - docker rmi $REPO:$COMMIT
  - docker images ;
  - docker container ls ;
  - docker ps -l ;

#after_success:
#  # Upload to docker if it's on the master branch
#  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
#      docker push $REPO ;
#    fi
#  # trigger docker-sketchbook (same tests based on docker-arduino)
#  - |-
#    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
#      if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
#        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/drtrigon%2Fdocker-sketchbook/requests ;
#      fi ;
#    fi

notifications:
  email: false
